---

- name: Install Ansible
  ansible.builtin.pip:
    name: ansible-core
    virtualenv: "{{ mailman3_distribute_maps_virtualenv_dir }}"
    virtualenv_command: "{{ mailman3_virtualenv_command | default(omit) }}"
    virtualenv_python: "{{ mailman3_virtualenv_python | default(omit) }}"

- name: Create playbook directory
  ansible.builtin.file:
    path: "{{ mailman3_distribute_maps_virtualenv_dir }}/etc"
    state: directory
    group: "{{ __mailman3_core_group_name }}"
    mode: "0750"

- name: Create playbook files (copy)
  ansible.builtin.copy:
    src: "distribute_maps.{{ item }}"
    dest: "{{ mailman3_distribute_maps_virtualenv_dir }}/etc/{{ item }}"
    group: "{{ __mailman3_core_group_name }}"
    mode: "0640"
  loop:
    - playbook.yml
    - ansible.cfg

- name: Create playbook files (template)
  ansible.builtin.template:
    src: "distribute_maps.{{ item }}.j2"
    dest: "{{ mailman3_distribute_maps_virtualenv_dir }}/etc/{{ item }}"
    group: "{{ __mailman3_core_group_name }}"
    mode: "0640"
  loop:
    - hosts

- name: Ensure Mailman Core user home directory exists
  ansible.builtin.user:
    name: "{{ __mailman3_core_user_name }}"
    create_home: true

- name: Create cron job
  ansible.builtin.cron:
    name: Distribute Mailman 3 Postfix Maps
    cron_file: ansible_mailman3_distribute_maps
    user: "{{ __mailman3_core_user_name }}"
    minute: "*/{{ mailman3_distribute_map_frequency | default(5) }}"
    job: >-
      cd {{ mailman3_distribute_maps_virtualenv_dir | quote }}/etc &&
      {{ mailman3_distribute_maps_virtualenv_dir | quote }}/bin/ansible-playbook playbook.yml
      >>{{ mailman3_core_log_dir }}/distribute_maps.log 2>&1
